### ISSUE TITLE
Document API and how we conceptualized it

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/pr-app#12]
### Your to-do

Document the below decisions and structure.

What should the API structure look like? E.g.:

1. Resource first
    * _/path-to-app/hammersmith/map_
    * _/path-to-app/hammersmith/read_
    * _/path-to-app/hammersmith/tei_
2. View type first
    * _/path-to-app/map/hammersmith_
    * _/path-to-app/read/hammersmith_
    * _/path-to-app/tei/hammersmith_

That is, do we ask first for the resource and then specify what we want to see or know about it, or do we specify the type of view we want and then the specific content item we want to render in that view?

### Issues you may encounter

Finding documentation of best practice in API syntax/semantics.

### Additional context

* We have API tutorial information in week 3 of our first Institute.
* Consult API for Map of Early Modern London. The documentation at https://mapoflondon.uvic.ca/BLOG10.htm is about requesting information about the repository, and not about requesting a specific view of a specific resource.

**Comment by djbpitt** [comment]
Useful tutorial (detailed, but no assumption of prior knowledge or experience): [Documenting APIs: A guide for technical writers and engineers](https://idratherbewriting.com/learnapidoc/).

Our task is simpler in some ways than the APIs described in guides and tutorials. Thoughts:

1. **We use only GET (not other REST verbs):** API guides imagine full CRUD interactions (create, read, update, delete), but our project is read-only.
1. **How much do we care about providing REST endpoints for site metadata?** API guides often focus on metadata and discovery, with endpoints (URIs) to learn about the site or project structure and resources. HATEOS (Hypermedia as the Engine of Application State, a REST constraint) supplies link relations that can guide subsequent queries (example at [Wikipedia](https://en.wikipedia.org/wiki/HATEOAS)). It isn't clear how much of this discovery matters for our target users.
1. **Thinking about HTTP status codes:** API guides often emphasize the importance of providing informative HTTP status codes in response headers. If, though, our controller handles a resource not found error, Jetty will return 200, since we are resolving the endpoint, which means thatJetty will not know that they're bad, and we would be responsible for overriding the Jetty status code. How much do we care? The status code won't matter to a human looking in a web browser, but it might be important for automated access by spiders and other automated consumers of content, etc.
1. Endpoints
    1. **Article content lists:** _http://(app-root)/articles?date=x&place=y_ That is, specify filtering as query parameters.
    1. **Individual articles:** _http://(app-root)/articles/article123?view=read_ That is, specify resource as the path and the view (reading view, raw TEI, others?) as a query parameter. 
    2. **Composite pages:** If default view is side-by-side (e.g., formatted reading view on left and facsimile image on right), should each panel have its own endpoint, with a separate endpoint for the composite page as a whole? That would make, say, all of the images or all of the TEI views accessible independently of their being embedded in a project page with boilerplate. All pages are composite to some extent since they have headers, footers, navigation, etc. We don't want to prohibit access to individual resources outside our front end (and they're all available to developers in our repo anyway), but how much do we care about prioritizing an API for that type of access?
    1. **Query parameters and defaults:** Query parameters are optional and we supply sensible defaults. Do we add the defaults explicitly to the rewritten query string?
    2. **Other resources.** Some are primarily textual (persons), others may be textual and non-textual (places will have text and perhaps mapping).

**Comment by gabikeane** [comment]
We will be revisiting Katherine Bode's A World of Fiction (just part 1) in issue #13

**Comment by gabikeane** [comment]
we are leaning toward the view type first approach. This is a result of our particular data being used more often in aggregate than by individual article (or even content-specific groups of articles). We imagine exposing the articles and groups through these paths like this:

/path-to-app/map/hammersmith

with Hammersmith being a group of articles from a particular place - any articles containing #hammersmith or any xml:id references contained by Hammersmith in the gazetteer.

/path-to-app/read/publisher/the-times

with The Times being a tei:publisher value available in the metadata, but the value is, in this case, plaintext

/path-to-app/read/date/1804-01-02

with the date being defined in the metadata, available at year/month/day levels

considering how to approach annotated guides / sets of content
https://cdhrdatasys.anu.edu.au/anfd/web/index.php?r=trove/search
https://melville.electroniclibrary.org/projects

Melville - very limited content, guides work as an entry point to texts and text features. Shelf, pick a book, pick a chapter, then features are surfaced to you
ANFD - expansive content (26k+ individual chapters), guides work as an entry point for interested researchers and are curated by machine learning. We guess that the researcher is taking a few texts she knows are about the topic (young adult fiction and bush fiction were the examples we looked at, counting some features in them and then finding chapters which have similar counts. Content guides focus on appealing to researchers who are likely to engage the content and perhaps improve it.

annotated guides as a research concept may be an intriguing discussion topic to explore.

**Comment by gabikeane** [comment]
restfulapi.net notes:

URIs have noun/noun/noun/action structure in traditional APIs. There's a transactional nature where final endpoint represents the action being done to this particular hierarchy of items/resources.

In our case, we're more interested in an action/noun sort of structure, which lends itself to the text-as-collection or text-as-edition.

Your own knowledge being constructed around the resource can be reflected within the design of the API.

**Comment by djbpitt** [comment]
@gabikeane The article at https://betterprogramming.pub/intent-based-rest-apis-or-an-alternative-to-crud-based-rest-apis-1815599db60a gives an example of a context where a verb-based API might be preferable to one designed to support CRUD. Worth a look, since it's somewhat different from the perspectives we've been exploring, but it intersects with our desire to design an API based more on project-specific needs than on implementing a general REST/CRUD paradigm.

**Comment by gabikeane** [comment]
see also https://github.com/Pittsburgh-NEH-Institute/pr-app/issues/16

**Comment by djbpitt** [comment]
Discussion finished; resolution implemented
