### ISSUE TITLE
Read part 1 of Bode

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/pr-app#13]
### Your to-do

@gabikeane @djbpitt Read part 1 of Kat Bode's _A world of fiction_. Goal: Should discoverability of API structure and further queries be a priority for our project? Look at what others have done.

**Comment by gabikeane** [comment]
"Modeling recognizes data as constructed, but only by the individual scholar; it does not provide a mechanism to interrogate the history of transmission preced- ing and perpetuated by the scholar’s engagement with the documen- tary record, including in its mass-digitized forms. The framework of the scholarly edition meets that challenge, presenting a structure to negotiate the incomplete and transactional nature of the documentary record and to represent the outcomes of that process" (Bode 38).

In what ways does an API re-introduce a new transactional structure, and if so what value can we create by recognizing it explicitly?

Bode answers immediately: "Adapted to the literary system, it offers a reliable foundation for data-rich literary history and for extending the insights gained from that field’s engage- ment with emerging digital infrastructure to the broader discipline" (38)

"One contribution this book aims to make is to expand and enrich the application of modeling for data-rich literary history by connecting it explicitly to descriptive bibliography" (41).

How does writing an API expand/enrich the application of modeling? Does it merely expose the model, or does it add another layer of knowledge structure? I do think it adds another layer 

May be worth revisting _Pamphlet II_
