### ISSUE TITLE
[BUG] Ambiguous title and bibliographic reference?

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/pr-app#20]
_parkghost_times_1804.xml_ and _stjamesparkghost_times_1804_ are unique records with unique content and `@xml:id` values, but they appear to have identical `<title>` values under `<titleStmt>` and identical `<bibl>` values under `<sourceDesc>`, and they were published on the same day. How should they be distinguished when rendered in a list of articles?

**Comment by gabikeane** [comment]
Revisit 'All the World' articles which are showing identically in search now.

**Comment by djbpitt** [comment]
Fixed by adding incipit tooltip (using `@title`)
