### ISSUE TITLE
Write documentation for unit testing with XQSuite

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/pr-app#24]
### Your to-do

Convert experimentation with testing in separate djbpitt/exist-sandbox repo to testing tutorial

### Issues you may encounter

None

### Additional context

**Comment by gabikeane** [comment]
- [] How to make the [script to create unit test HTML](https://github.com/djbpitt/exist-sandbox/blob/main/test/xqs/create-html-report.sh) output accessible in eXist-db
