### ISSUE TITLE
Update Yeoman instructions to include creating GitHub repo as origin

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/pr-app#29]
### Your to-do

Our Yeoman instructions create a local repo with a single branch called `master`. The conventional name for a main branch is now `main`; we need to update the instructions to include `git branch -m main`.

We need to add instructions for creating a matching main branch on GitHub and configuring as origin. 

### Issues you may encounter

When creating origin at GitHub must tread carefully to avoid unrelated histories.

**Comment by gabikeane** [comment]
To do on 2022-07-02

**Comment by EmmaSchwarz** [comment]
Finished on 2022-07-02.
