### ISSUE TITLE
Discuss and decide: Link to stories by filename or @xml:id?

### ISSUE THREAD

**Issue by djbpitt** [Pittsburgh-NEH-Institute/pr-app#33]
### To discuss:

We currently link to files by filename to access the reading view and the TEI view. Should we use the `@xml:i`d attribute on the root `<TEI>` element instead.

**Comment by gabikeane** [comment]
Update all modules to use the @xml:id attributes.

**Comment by djbpitt** [comment]
Decided to use `@xml:id`
