### ISSUE TITLE
Search functionality throws an XML error[BUG]

### ISSUE THREAD

**Issue by MedievalMatt** [Pittsburgh-NEH-Institute/pr-app#65]
### Expected behavior
The search page will open up and properly display

### Actual behavior
An XML error message is dumped to the page, stating:

<exception>
<path>/db/apps/pr-app/modules/search.xql</path>
<message>
err:XPTY0004 Invalid cardinality for variable $incipit. Expected exactly one, got empty [at line 197, column 14, source: /db/apps/pr-app/modules/search.xql]
</message>
</exception>

### Reproduction steps
Install the Ghost repository to the exist page via exist.
open your local installation
Attempt to open the search page.

### Please provide the following
*   Java Version: 1.8.0_333
*   exist-db version: 6.0.1 51506fc97a9e5bb55fdea71fc76def2c9d402886 20220209234135
*   pr-app version: Not Sure
*   OS version: Windows 11 (22H2)

**Comment by djbpitt** [comment]
@MedievalMatt When you have a moment (okay, two moments), can you please try the strategy suggested above by @MasonGobat and let us know whether it helps?

**Comment by MedievalMatt** [comment]
HI, that resolves the issue so long as exist doesn't run as a service.  Thanks!
